#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
  max_column=100
  windows_leader = "ù"
  relativenumber = false

  filemanager = "defx"
  enable_vimfiler_gitstatus = true
  enable_googlesuggest = 1 # Not working?

  buffer_index_type = 0
  statusline_separator = "arrow"
  statusline_inactive_separator = "bar"
  enable_tabline_filetype_icon = true

  bootstrap_before = "config#before"
  # bootstrap_after = "config#after"

  automatic_update = true

  colorscheme = "dracula"
  colorscheme_bg = "dark"
  enable_guicolors = true

[[layers]]
  name = "format"
  format_on_save = true

[[custom_plugins]]
  repo = "dracula/vim"

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "smart" # Expands snippets as well
  auto_completion_tab_key_behavior = "complete" # Ctrl-n / Ctrl-p for navigation

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "github"

[[layers]]
  name = 'default' # For clipboard copy/paste

[[layers]]
  name = 'colorscheme' # Enables non-default colorschemes

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = "tools"

[[layers]]
  name = "denite"

[[layers]]
  name="incsearch"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

# https://spacevim.org/layers/language-server-protocol/
# [[layers]]
  # name = "lsp"
  # filetypes = ["typescript", "rust", "sh"]
  # filetypes = ["rust"]

[[layers]]
  name = "lang#typescript"

# https://spacevim.org/layers/lang/rust/
[[layers]]
  name = "lang#rust"
  recommended_style = true
  # see https://github.com/SpaceVim/SpaceVim/issues/4570
  # rustfmt_cmd = ["rustup", "run", "nightly", "rustfmt"]
[layers.override_cmd]
  # rust = ["rls"]
  # rust = ["cargo", "run", "nightly", "rust-analyzer"] # ??
  # rust = ["rust-analyzer"]

# https://spacevim.org/layers/lang/sh/
[[layers]]
  name = "lang#sh"

# https://spacevim.org/layers/lang/php/
[[layers]]
  name = "lang#php"
